### ISSUE TITLE
Bad coding

### ISSUE THREAD

**Issue by sen1** [taariley/pwp-capstones#3]
```
if (word in frequency_table.keys()) == True:
```

just a bad code. `x in y` returns a boolean True/False. So comparing with `==True` does not change anything. 

You can simply do `word in frequency_table`, nothing else. Even better approach is:
```
if word_count_frequency.get(word):
```
if the word, not found, it wont raise a `keyerror`.

**Comment by taariley** [comment]
Makes sense, I hope to build more familiarity, which will help find more efficient solutions.
